### ISSUE TITLE
two errors when compiling on macOS Big Sur 11.5.1

### ISSUE THREAD

**Issue by jzevin** [linusmossberg/light-field-renderer#1]
Hi, I don't really know what I'm doing, but I after running `make` in the `build` dir of the repo, it gets to about **83%** then borks out with _13 warnings and 2 errors_. Any help would be appreciated and thanks for your time. [full cli output to => errors.pdf](https://github.com/linusmossberg/light-field-renderer/files/7028094/errors.pdf)

```[ 83%] Building CXX object CMakeFiles/light-field-renderer.dir/source/core/camera-array.cpp.o
/Users/jz/Desktop/light-field-renderer/source/core/camera-array.cpp:107:32: error: use of undeclared identifier 'GL_RG'
        case 2: pixel_format = GL_RG; break;
```
_____
```            ^
/Users/jz/Desktop/light-field-renderer/source/core/camera-array.cpp:126:9: error: use of undeclared identifier 'glGenerateMipmap'
        glGenerateMipmap(GL_TEXTURE_2D);
```

**Comment by linusmossberg** [comment]
Hi!

Thanks for letting me know. The only thing that stands out to me is that the Metal backend is selected automatically in your case. What happens if you assign `OpenGL` to the CMake variable `NANOGUI_BACKEND`? I.e. by calling the CMake command as:
```
cmake .. -DNANOGUI_BACKEND=OpenGL
```

**Comment by linusmossberg** [comment]
This option is forced as of commit 28e87db anyhow, which hopefully fixes it. Otherwise it's likely due to limited OpenGL support in macOS, which I can't do anything about.

**Comment by jzevin** [comment]
that worked thanks!
